export { default as Start } from '@/components/page/Start.page'
export { default as Loading } from '@/components/page/Loading'
export { default as OnlyOneKeiba } from '@/components/page/OnlyOneKeiba.page'
export { default as BaneiHistory } from '@/components/page/BaneiHistory.page'
export { default as BaneiRoots } from '@/components/page/BaneiRoots.page'
